metricbeat.modules:
  - module: prometheus
    metricsets: ["collector"]
    enabled: true
    period: 10s
    hosts: ["prometheus:9090"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"